#!/bin/bash
set -e

SERVER_IP="38.19.198.52"
SERVER_USER="root"

echo "=== Mekan360 Deploy Scripti ==="
echo "Sunucu: $SERVER_IP"

echo ""
echo "1. Once frontend build alin:"
echo "   cd frontend && npm install && npm run build"
echo ""
echo "2. Sunucuya SSH ile baglanin:"
echo "   ssh $SERVER_USER@$SERVER_IP"
echo ""
echo "3. Sunucuda kurulum scriptini calistirin (ilk seferlik):"
echo "   bash server-setup.sh"
echo ""
echo "4. Dosyalari sunucuya kopyalayin (yerel makineden):"
echo "   scp -r frontend/build/* $SERVER_USER@$SERVER_IP:/var/www/mekan360/frontend/"
echo "   scp backend/server.py backend/requirements.txt $SERVER_USER@$SERVER_IP:/var/www/mekan360/backend/"
echo ""
echo "5. Sunucuda backend'i kurun:"
echo "   cd /var/www/mekan360/backend"
echo "   python3 -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "6. Systemd servisini kurun:"
echo "   cp /path/to/mekan360-backend.service /etc/systemd/system/"
echo "   systemctl daemon-reload"
echo "   systemctl enable mekan360-backend"
echo "   systemctl start mekan360-backend"
echo ""
echo "7. Nginx'i yapilandirin:"
echo "   cp /path/to/nginx-mekan360.conf /etc/nginx/sites-available/mekan360"
echo "   ln -sf /etc/nginx/sites-available/mekan360 /etc/nginx/sites-enabled/"
echo "   rm -f /etc/nginx/sites-enabled/default"
echo "   nginx -t"
echo "   systemctl restart nginx"
echo ""
echo "=== Kurulum Tamamlandi ==="
